
title: lessthantwentydollars
author: Kristofferson Carillo
email: peiwebdev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Cool shit you can buy for less than twenty dollars, no bullshit. The best products on amazon for less than 20$ .  
baseurl: "" # the subpath of your site, e.g. /blog
url: "lessthantwentydollars.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: peisop
lang: english
github_username:  jekyll

# Build settings
livereload: true
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-livereload
  - jekyll-seo-tag
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
